#格式说明:值都要用引号括起来，包括数字! 数组格式为["foo","bar"],某一项格式错误会解析失败!
#井号为注释，如果不需要某个可选的内容，就把#放在这一行的开头，注释掉该行让该行失效

[base]
# 产品名称（必填）
product = "最强门派"

# 更新时间（必填）
update_at = "2021-01-02"

# 主体名称（必填）
entity_name = "南京魔度互娱有限公司"

# 联系人邮箱（必填）
email = "iian9411@sina.cn"

# 主体地址（必填）
address = "江苏省南京市雨花台区软件大道21号舜天集团H栋三层"

# 联系电话（必填）
tel="025-869806863"

# 注销路径（必填）
logout= "点击头像-设置-注销"

# 隐私协议路径（必填）
privacy= "点击我的-设置-隐私政策"

################################################################
# 基础功能，根据产品实际情况填写（可选）
contents = [""]

# 附加功能，根据产品实际情况填写（可选）
extras=[""]

# 推送关闭路径，适用于有推送功能的APP，会增加"自主管理推送"的内容（可选）
push= "点击我的-设置-关闭推送"

# 游戏产品需要此项,将值修改为true,会额外增加"防沉迷"的内容（可选）
is_game = "true"

# 如果将值修改为true,会从apk分析得到产品名称，覆盖上面的product选项（可选）
product_name_auto_generated = "false"
################################################################
# 如果产品需要有自己的权限说明，在这里修改描述
# 提示：下面只是示例，第一个是修改，第二个是新增
# 如果没有，请将下面的示例注释掉(在每一行开头都添加#才能都注释掉)（可选）
#[[permissions]]
#constant="android.permission.ACCESS_NETWORK_STATE"
#scenario="此权限的使用场景及目的111"

#[[permissions]]
#constant="com.xxx.yyy"
#scenario="此权限的使用场景及目的222"

################################################################
#有些sdk可能静态检测检测不出来，在下面添加这些sdk的描述，提示：下面只是示例
# 提示：下面只是示例
# 如果没有，请将下面的示例注释掉(在每一行开头都添加#才能都注释掉)（可选）
[[sdks]]
pkg="com.tencent.smtt"